### ISSUE TITLE
Crash when icalendar event has same start and end dates

### ISSUE THREAD

**Issue by nikialeksey** [nikialeksey/meerk#10]
```
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    calendar.sync()
  File "/Users/a327/Downloads/meerk-master/meerk/calendar/LoggableCalendar.py", line 49, in sync
    self.origin.sync()
  File "/Users/a327/Downloads/meerk-master/meerk/calendar/CompositeCalendar.py", line 47, in sync
    calendar.sync()
  File "/Users/a327/Downloads/meerk-master/meerk/calendar/IcsCalendar.py", line 51, in sync
    datetime.now() + timedelta(days=1)
  File "/Users/a327/Downloads/meerk-master/meerk/intervals/SimpleIntervals.py", line 46, in add
    dtend = self.__without_tzinfo(component['dtend'].dt)
  File "/Library/Python/2.7/site-packages/icalendar/caselessdict.py", line 42, in __getitem__
    return super(CaselessDict, self).__getitem__(key.upper())
KeyError: u'DTEND'
```

**Comment by nikialeksey** [comment]
Fixed!
